#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $ new-pi <IP_ADDRESS>"
    exit 1
fi

ip=$1
ssh-keygen -f "/home/${USER}/.ssh/known_hosts" -R "${ip}"

host_identifier="pi@${ip}"
ssh-copy-id ${host_identifier}

